config/routes.rb
Rails.application.routes.draw do
  root 'books#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :books do

    get :new_book
    post :create_book
    post :create_book_csv
    get :my_books
    post :overdue_book
    get :home
    get :notification_book
   

  end

  resources :books do
    get '/page/:page', action: :home, on: :collection
  end

  namespace :library do

    get :new_library
    post :create_library
    get :home

  end

  get "edit_book/:id" => 'books#edit_book'
  get "delete_book/:id" => 'books#delete_book'
  get "history_book/:id" => 'books#history_book'
  get "book_detail/:id" => 'books#book_detail'
  get "book_detail/copy_history/:id" => 'books#copy_history'
  get "return_book/:id" => 'books#return_book'
  get "borrow_book/:id" => 'books#borrow_book'
 

  get "library/edit_library/:id" => 'library#edit_library'
  get "library/delete_library/:id" => 'library#delete_library'
  get "library/library_detail/:id" => 'library#library_detail'
 

end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :library
    validates :title, :genre, :subgenre, :pages, :copies, presence: true
    paginates_per 20


    enum activated: [:no, :yes]
    after_initialize :set_default_activated, :if => :new_record?
    def set_default_activated
        self.activated ||= :yes
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except:[:home]
  before_action :authenticate_admin!, only:[:create_book, :create_book_csv, :edit_book, :delete_book ]
  
  def home
   
    @books = Book.where('activated = 1').order('title').page(params[:page]).per(10)

    # if params[:title].present?
    #   @books= @books.where("title ILIKE ?", "%#{params[:title]}%").page params[:page]
    # end

    if params[:search].present?
      book_search = params[:search]
      @books= @books.where("title ILIKE ?", "%#{book_search}%").page(params[:page]).per(10)

      respond_to do |format|
        format.html
        format.turbo_stream { render partial: "books_list", locals: { books: @books}}
      end
    end

    

  end

  def create_book

    book_id = params[:id]
    params_copies = params[:copies].to_i
    qnty_exist_copies = 0

    library_name = params[:library]
    libraries = Library.where('branch_name=?',library_name).take

    if libraries.blank?
        library_create = Library.new
        library_create.branch_name = params[:library]
        library_create.address = 'Canada'
        library_create.phone_number = 0
        library_create.save
        @library_id = library_create.id
    else
      @library_id = libraries.id
    end

    @book = Book.new if book_id.blank?
    @book = Book.find(book_id) if !book_id.blank?
   
    @book.title = params[:title]
    @book.author = params[:author]
    @book.genre = params[:genre]
    @book.subgenre = params[:subgenre]
    @book.pages = params[:pages]
    @book.publisher = params[:publisher]
    @book.copies = params_copies
    @book.library_id = @library_id
    @book.save

    qnty_exist_copies = CopyBook.where('copy_books.deactived_copy = 0 and books_id=?',book_id).count  if !book_id.blank?
    qnty_exist_copies = qnty_exist_copies.to_i   

    if qnty_exist_copies < params_copies

      cont_copies = 1
      add_copies = (params_copies - qnty_exist_copies)

      notifications = EmailNotification.where('activated = true and book_id=?', book_id)

      send_email_notification = send_email_notify(notifications,add_copies)

      while cont_copies <= add_copies do

        new_copy_number = qnty_exist_copies + cont_copies
        copy_book = CopyBook.where('copy_books.deactived_copy = 1 and books_id=? and copy_number=?',book_id, new_copy_number).take
        copy_book = CopyBook.new if copy_book.blank?
        copy_book.deactived_copy = 0 if !copy_book.blank?
        copy_book.books_id = @book.id
        copy_book.copy_number = new_copy_number
        copy_book.save
        cont_copies += 1

      end
    elsif qnty_exist_copies > params_copies

      quit_copy = (qnty_exist_copies - params_copies)
      new_number_copy = params_copies
     
      while new_number_copy < qnty_exist_copies  do
        
        copy_book = CopyBook.where('deactived_copy = 0 and copy_number=? and books_id=?',qnty_exist_copies,book_id ).take
        copy_book.deactived_copy = 1
        copy_book.save
        qnty_exist_copies -= 1
      end
    end

    if !book_id.blank?

      new_available_copies = CopyBook.where('deactived_copy = 0 and copy_status=0 and books_id=?',book_id).count
      available_copies_book = Book.find(@book.id)
      available_copies_book.copies = new_available_copies
      available_copies_book.save
      
    end

    redirect_to '/', notice: "Book created"

  end

  def create_book_csv

    require 'csv'

    file = params[:file_csv]
    cont_books = 0
    qnty_exist_copies = 0
    name_file = file.original_filename

    table = CSV.parse(File.read(file.tempfile), headers: true)

    libraries = Library.all
    
    if !file.blank?
      table.each_with_index do |sh,idx|

        library_name = sh[0]
        library = libraries.where('branch_name=?',library_name).take
    
        if library.blank?
            library_create = Library.new
            library_create.branch_name = library_name
            library_create.address = 'Canada'
            library_create.phone_number = 0
            library_create.save
            @library_id_csv = library_create.id
        else
          @library_id_csv = library.id
        end

        params_copies = sh[7].to_i

        title_book = sh[1]
        @book_csv = Book.where('title=? and library_id = ?',title_book,@library_id_csv).take if !title_book.blank?
        @book_csv = Book.new if @book_csv.blank?
        @book_csv.title = title_book
        @book_csv.author = sh[2]
        @book_csv.genre = sh[3]
        @book_csv.subgenre = sh[4]
        @book_csv.pages = sh[5]
        @book_csv.publisher = sh[6]
        @book_csv.copies = params_copies
        @book_csv.library_id = @library_id_csv
        @book_csv.save

        cont_books +=1

        qnty_exist_copies = CopyBook.where('copy_books.deactived_copy = 0 and books_id=?',@book_csv).count  if !@book_csv.blank?
        qnty_exist_copies = qnty_exist_copies.to_i   
    
        if qnty_exist_copies < params_copies
    
          cont_copies = 1
          add_copies = (params_copies - qnty_exist_copies)
          
          while cont_copies <= add_copies do
    
            new_copy_number = qnty_exist_copies + cont_copies
            copy_book = CopyBook.where('copy_books.deactived_copy = 1 and books_id=? and copy_number=?',@book_csv, new_copy_number).take
            copy_book = CopyBook.new if copy_book.blank?
            copy_book.deactived_copy = 0 if !copy_book.blank?
            copy_book.books_id = @book_csv.id
            copy_book.copy_number = new_copy_number
            copy_book.save
            cont_copies += 1
    
          end
        elsif qnty_exist_copies > params_copies
    
          quit_copy = (qnty_exist_copies - params_copies)
          new_number_copy = params_copies
         
          while new_number_copy < qnty_exist_copies  do
            
            copy_book = CopyBook.where('copy_books.deactived_copy = 0 and copy_number=? and books_id=?',qnty_exist_copies,@book_csv ).take
            copy_book.deactived_copy = 1
            copy_book.save
            qnty_exist_copies -= 1
          end
        end
        
      end

      redirect_to '/books/new_book.html', notice: "Total books processed #{cont_books}"
    else
      redirect_to '/books/new_book.html', notice: "No Records"
    end
    
    
  end

  def edit_book
    book_id = params[:id]
    @books = Book.find(book_id)
    @copies_edit_book = CopyBook.where('books_id=? and copy_books.deactived_copy = 0',book_id).count
    @library_edit_book = Library.find(@books.library_id)
  end

  def delete_book

    book_id=params[:id]
    @book_delete = Book.find(book_id)
    @book_delete.activated = 0
    @book_delete.save

    redirect_to '/', notice: "Book deleted"
    
  end

  def borrow_book

    book_id = params[:id]

    copies_borrow = CopyBook.where('deactived_copy = 0 and copy_status = 0 and books_id=?',book_id ).first


    copy_number = copies_borrow.copy_number

    @borrow = BorrowBook.new
    @borrow.book_id = book_id
    @borrow.user_id = current_user.id
    @borrow.copy_number = copy_number
    @borrow.borrow_date = DateTime.current.to_date
    @borrow.due_date = (DateTime.current.to_date + 7)
    @borrow.copy_book_id = copies_borrow.id
    @borrow.save

    copy_book = CopyBook.find(copies_borrow.id)
    copy_book.copy_status = 1
    copy_book.save

    new_number_copies =  (CopyBook.where('deactived_copy = 0 and copy_status = 0 and books_id=?',book_id ).count).to_i

    book = Book.find(book_id)
    book.copies = new_number_copies
    book.save

    redirect_to '/books/my_books.html', notice:"Book borrowed"
    
  end

  def my_books
    
    @my_books = BorrowBook.where('user_id=?',current_user.id).order('status')
    time_end = DateTime.current.to_date

  end

  def return_book

    borrow_id = params[:id]
    borrow_book = BorrowBook.find(borrow_id)
    borrow_book.return_date = DateTime.current.to_date
    borrow_book.status = 1
    borrow_book.save

    book = Book.find(borrow_book.book_id)
   
    copy_book = CopyBook.where('copy_books.deactived_copy = 0 and books_id=? and copy_number=?', book.id, borrow_book.copy_number ).take  
    copy_book.copy_status = 0
    copy_book.save

    new_number_copies = (CopyBook.where('deactived_copy = 0 and copy_status = 0 and books_id=?',book.id ).count).to_i

    book.copies = new_number_copies
    book.save

    notifications = EmailNotification.where('activated = true and book_id=?', book.id)

    send_email_notification = send_email_notify(notifications,new_number_copies)

    redirect_to '/books/my_books', notice: "Book returned"

  end

  def book_detail

    book_id = params[:id]
    @book = Book.find(book_id)
   
    @copy_book_details = CopyBook.getTitle(book_id)

  end

  def copy_history

    copy_id = params[:id]
    copy_book = CopyBook.find(copy_id)
    
    @copy_history_details = CopyBook.getcopyhistory(copy_book.books_id,copy_book.copy_number)

  end

  def notification_book

    book_id = params[:id]
    user_id = current_user.id

    notifications = EmailNotification.where('activated = true and user_id=? and book_id=?', user_id, book_id )

    if notifications.blank?

      notification = EmailNotification.new
      notification.user_id = user_id
      notification.book_id = book_id
      notification.request_date = DateTime.current.to_date
      notification.save

      #NotifyBookMailer.send_mail_notify.deliver_now

      redirect_to '/', notice: 'Active notification'

    else

      redirect_to '/', notice: 'Active notification'

    end

  end

  def send_email_notify(notifications,copies)

    qnt_emails = notifications.length.to_i
    new_copies = copies.to_i

    if new_copies > qnt_emails

      notifications.each do |notification|
        user_email = User.find(notification.user_id)
        user_email = user_email.email
        book_title = Book.find(notification.book_id)

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books_list.html.erb
<% if books.any? %>
    <% books.each do |book| %>
        <div class="templatemo_product_box">
            <table>
                <tr><th class="title_book_table" scope="row" colspan="2"><%=book.title.upcase%></th></tr>
            </table> 
            <span>
                <% if book.copies< 1%>
                    <button class="send_borrow"><%= link_to 'No copies available, notify me', books_notification_book_path(id: book.id),class: "send_borrow", :style=>'text-decoration : none; color:white' %></button>
                <%else%>
                    <% if current_user %>
                        <% if current_user.admin? %>
                            <a href="/" class="send_borrow"><button disabled class="no_copies">Borrow</button></a>
                        <% else %>
                            <a href="/borrow_book/<%=book.id%>" class="send_borrow"><button class="send_borrow">Borrow</button></a>
                            <% end %>
                    <% else %>
                        <a href="/users/sign_in" class="send_borrow"><button class="send_borrow">Borrow</button></a>
                    <%end%>
                <%end%>
            </span>
            <table>
                <tr><td>Author:</td>
                <td><%=book.author? ? book.author : 'No information'%></td></tr>
                <tr><td>Genre:</td>
                <td><%=book.genre.capitalize%></td></tr>
                <tr><td>Subgenre:</td>
                <td><%=book.subgenre.capitalize%></td></tr>
                <tr><td>Pages:</td>
                <td><%=book.pages%></td></tr>
                <tr><td>Publisher:</td>
                <td><%=book.publisher? ? book.publisher : 'No information'%></td></tr>
                <tr><td>Available Copies:</td>
                <td><%=book.copies%></td></tr>
                <tr><td>Library:</td>
                <td><a href="/library/library_detail/<%=book.library.id%>", style='text-decoration : none'><%=book.library.branch_name.capitalize%></a></td></tr>
            </table>
            <% if current_user %>
                <h3><%= link_to "Book details", "book_detail/#{book.id}",:style=>'text-decoration : none' %></h3>
                <% if current_user.admin? %>
                    <h3><%= link_to "Edit", "edit_book/#{book.id}",:style=>'text-decoration : none' %></h3>
                    <h3><%= link_to "Delete", "delete_book/#{book.id}",  data: { turbo_confirm: 'Are you sure?'}, :style=>'text-decoration : none'%></h3>
                <%end%>
            <%end%>
        </div>
    <%end%>
<% else%>
    <h2>No data</h2>
<% end %>

<h3><%= paginate books %></h3>

app/views/books/book_detail.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Detail Book</title>
    </head>
    <body>
        <div id="templatemo_container">
            <div id="templatemo_menu">
                <ul>
                    <% if current_user %>
                        <li><a href="/" class="current">Hello <%= current_user.email %></a></li>
                        <li><a href="/">Home</a></a></li>
                        <% if current_user.admin? %>
                            <li><a href="/books/new_book.html">Create Books</a></a></li>
                        <% else %>
                            <li> <a href="/books/my_books">My Books</a></li>            
                        <% end %>
                        <li><%= link_to "Log off", destroy_user_session_path, 'data-turbo-method': :delete%></li> 
                    <% else %>
                        <li><a href="/" class="current">You are not sign in</a></li>  
                        <li><%= link_to "Sign up", new_user_registration_path %></li> 
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div> 
    
            <div id="templatemo_header">
            </div> 
            
            <div id="templatemo_content">
                <div id="templatemo_content_right">
                    <% if !@copy_book_details.blank? %>
                        <div class="title_center">
                            <h2 class="h2_class"><%=@copy_book_details.first.title.upcase%></h2>
                        </div>
                        <% @copy_book_details.each do |copy_book_detail| %>
                            <div class="templatemo_product_box_detail">
                                <table>
                                    <tr><th class="title_detail_table" scope="row" colspan="2">Copy #:<%=copy_book_detail.copy_number %></th></tr>
                                    <tr><td>Status: </td>
                                    <td><%=copy_book_detail.copy_status%></td>
                                </table>
                                <h3><%= link_to "Copy history ", "copy_history/#{copy_book_detail.id}",:style=>'text-decoration : none' %></h3>
                            </div>
                        <%end%>
                    <% end %>
                </div> 
            </div>
            
            <a href="/" id="back_btn" style="text-decoration:none; text-align:center">Back</a>
            
            <div id="templatemo_footer">
                <a href="/">Development on Ruby on Rails</a> | 
                Copyright © 2022 <a href="https://linkedin.com/in/ing-john-carlos-jejen-corredor/"><strong>John Jejen</strong></a> 
            </div> 
        </div>
    </body>
</html>

app/views/books/copy_history.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>copy History  book</title>
    </head>
    <body>
         <div id="templatemo_container">
            <div id="templatemo_menu">
                <ul>
                    <% if current_user %>
                        <li><a href="/" class="current">Hello <%= current_user.email %></a></li>
                        <li><a href="/">Home</a></a></li>
                        <% if current_user.admin? %>
                            <li><a href="/books/new_book.html">Create Books</a></a></li>
                        <% else %>
                            <li><a href="/books/my_books">My Books</a></li>            
                        <% end %>
                        <li><%= link_to "Log off", destroy_user_session_path, 'data-turbo-method': :delete%></li> 
                    <% else %>
                        <li><a href="/" class="current">You are not sign in</a></li>  
                        <li><%= link_to "Sign up", new_user_registration_path %></li> 
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div> 
    
            <div id="templatemo_header">
            </div>
            
            <div id="templatemo_content">
                <div id="templatemo_content_right">
                    <% if !@copy_history_details.blank? %>
                        <div class="title_center">
                            <h2 class="h2_class"><%=@copy_history_details.first.title.upcase%></h2>
                        </div>
                        <div class="subtitle_center">
                            <h2 class="h2_class">Copy #<%=@copy_history_details.first.copy_number%></h2>
                        </div>
                        <% @copy_history_details.each do |copy_history_detail| %>
                            <div class="templatemo_product_box_history">
                                <table>
                                    <tr><th class="title_detail_table" scope="row" colspan="2">Borrow # <%=copy_history_detail.id%></th></tr>
                                    <tr><td>Status</td>
                                    <% if copy_history_detail.status == 0%>
                                        <td>Borrowed</td>
                                    <% else %>
                                        <td>Returned</td>
                                    <% end %>
                                    </tr>
                                    <tr><td>Borrow Date</td>
                                    <td><%=copy_history_detail.borrow_date%></td></tr>
                                    <tr><td>Due Date</td>
                                    <td><%=copy_history_detail.due_date%></td></tr>
                                    <tr><td>Return Date</td>
                                    <td><%=copy_history_detail.return_date%></td></tr>
                                    <tr><td>User</td>
                                    <td><%=copy_history_detail.email%></td></tr>
                                </table>
                            </div>
                        <%end%>
                    <% else %>
                        <div class="title_center">
                            <h2 class="h2_class">No records</h2>
                        </div>
                    <%end%>
                </div>
            </div>
            <%= link_to "Back", :back ,:style=>'text-decoration : none;text-align:center', :id=>"back_btn" %>
            <div id="templatemo_footer">
                <a href="/">Development on Ruby on Rails</a> | 
                Copyright © 2022 <a href="https://linkedin.com/in/ing-john-carlos-jejen-corredor/"><strong>John Jejen</strong></a> 
            </div> 
        </div>
    </body>
</html>

app/views/books/edit_book.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Edit Book</title>
	</head>
	<body>
        <div id="templatemo_container">
            <div id="templatemo_menu">
                <ul>
                    <li><a href="/" class="current">Hello <%= current_user.email %></a></li>
                    <li><a href="/">Home</a></a></li>
                        <% if current_user.user? %>
                        <script type="text/javascript">
                            alert("Access Denied!");
                            window.location.href="/"
                        </script>
                    <% end %>
                    <li><%= link_to "Log off", destroy_user_session_path, 'data-turbo-method': :delete%></li> 
                    <li><a href="/">Back</a></li>
                </ul>
            </div> 
    
            <div id="templatemo_header">
            </div> 
            
            <div id="templatemo_content">
                <div id="templatemo_content_new">
                    <div class="title_center">
                        <h2 class="h2_class">Edit book</h2>
                    </div>
                    <div class="content_new">
                        <%= form_tag({:controller => "books", :action => "create_book"},:method => "post", :multipart => true, :class =>'') do %>
                            <table>
                                <tr>
                                    <td id="font_create">Title</td>
                                    <td id="font_create"><input type="text" name="title" required="" value="<%= !@books.blank? ?  @books.title : ' '%>" ></td>
                                    <td id="font_create">Author</td>
                                    <td id="font_create"><input type="text" name="author" value="<%= !@books.blank? ?  @books.author : ' '%>" ></td>
                                    
                                </tr>
                                <tr>
                                    <td id="font_create">Genre</td>
                                    <td id="font_create"><input type="text" name="genre"  required="" value="<%= !@books.blank? ?  @books.genre : ' '%>" ></td>
                                    
                                    <td id="font_create">Subgenre</td>
                                    <td id="font_create"><input type="text" name="subgenre"  required="" value="<%= !@books.blank? ?  @books.subgenre : ' '%>" ></td>
                                    
                                </tr>
                                <tr>
                                    <td id="font_create">Pages</td>
                                    <td id="font_create"><input type="number" name="pages"  required="" value="<%= !@books.blank? ?  @books.pages : ' '%>" ></td>
                                    
                                    <td id="font_create">Publisher</td>
                                    <td id="font_create"><input type="text" name="publisher" value="<%= !@books.blank? ?  @books.publisher : ' '%>"></td>
                                    
                                </tr>
                                <tr>
                                    <td id="font_create">Total Copies</td>
                                    <td id="font_create"><input type="number" name="copies"  required="" value="<%= !@copies_edit_book.blank? ?  @copies_edit_book : ' ' %>" ></td>
                                    <td id="font_create">Library</td>
                                    <td id="font_create"><input type="text" name="library" value="<%= !@library_edit_book.blank? ?  @library_edit_book.branch_name : ' '%>"></td>
                                </tr>
                                <tr></tr>
                                <tr></tr>
                                <input type="hidden" name="id" value ="<%= @books.id%>" >
                            </table>
                           <p>
                                <input type="submit"  value="Save" id="create_btn" >
                                <a href="/" id="back_btn" style="text-decoration:none; text-align:center">Back</a>
                            </p>
                        <%end%>
                    </div>
                </div> 
            </div>
            <div id="templatemo_footer">
                <a href="/">Development on Ruby on Rails</a> | 
                Copyright © 2022 <a href="https://linkedin.com/in/ing-john-carlos-jejen-corredor/"><strong>John Jejen</strong></a> 
            </div> 
        </div>
	</body>
</html>

app/views/books/home.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Books</title>
    </head>
    <body>
        <div id="templatemo_container">
            <div id="templatemo_menu">
                <ul>
                    <% if current_user %>
                        <li><a href="/" class="current">Hello <%= current_user.email %></a></li>
                        <% if current_user.admin? %>
                            <li><a href="/">Books</a></a></li>
                            <li><a href="/library/home.html">Libraries</a></a></li>
                            <li><a href="/books/new_book.html">Create Books</a></a></li>
                            <li><a href="/library/new_library.html">Create Library</a></a></li>
                        <% else %>
                            <li><a href="/">Home</a></a></li>
                            <li> <a href="/books/my_books">My Books</a></li>            
                        <% end %>
                        <li><%= link_to "Log off", destroy_user_session_path, 'data-turbo-method': :delete%></li> 
                    <% else %>
                        <li><a href="/" class="current">You are not sign in</a></li>  
                        <li><%= link_to "Sign up", new_user_registration_path %></li> 
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div> 
    
            <div id="templatemo_header">
               
            </div> 
              <h1>Books List</h1>
            <div id="templatemo_content">
                <div id="templatemo_content_right">
                    <div class="subtitle_center">
                        <h2 class="h2_class"><%= flash[:notice] %><h2>
                    </div>
                    <div >
                        <%= form_with url: books_home_path, method: :get, local: :true, id: "search_form" do %>
                        <%= label_tag :search, "Search:" %>
                        <%= text_field_tag :search, params[:search], id: "search_input", class: "search", placeholder: "Search", autofocus: true%>
                        <%= button_tag "Search", class: "btn_search" %>
                        <% end %>

                    </div>
                    <div id="spinner" class="spinner"></div>
                    <%= turbo_frame_tag "books_results" do %>
                        <%= render partial: "books_list", locals: {books: @books} %>
                    <% end %>
                    
                    
                </div> 
            </div>
            <div id="templatemo_footer">
                <a href="/">Development on Ruby on Rails</a> | 
                Copyright © 2022 <a href="https://linkedin.com/in/ing-john-carlos-jejen-corredor/"><strong>John Jejen</strong></a> 
            
            </div> 
        </div>
    </body>
</html>
<script>
    document.addEventListener("turbo:load", () => {
        const searchInput = document.getElementById("search_input")
        const searchForm = document.getElementById("search_form")

        if (searchInput) {
            searchInput.addEventListener("input", function(){
                clearTimeout(this.searchTimer);
                this.searchTimer = setTimeout(() => {
                    Turbo.visit(`${searchForm.action}?search=${searchInput.value}`,{ frame: "books_results"});
                },300 );
            });
        }

    });
    document.addEventListener("turbo:before-fetch-request", function() {
        document.getElementById("spinner").style.display = "block";
    });

    document.addEventListener("turbo:before-fetch-response", function() {
        document.getElementById("spinner").style.display = "none";
    });

    document.addEventListener("turbo:before-fetch-response", function() {
        const results = document.getElementById("books_results");
        if (results) {
            results.classList.add("fade-in");
        }
    });
    document.addEventListener("turbo:frame-render", function(event) {
        const frame = event.target;
        frame.querySelectorAll("ul").forEach(element => {
            element.classList.add("slide-in");
        });
    });



</script>